package contract

import (
	"strings"

	"extent/internal/analyzer"
)

func Render(result analyzer.Result) string {
	name := result.ServiceName
	if strings.TrimSpace(name) == "" {
		name = "app"
	}
	database := len(result.DatabaseLibraries) > 0
	queues := len(result.Queues) > 0
	externalHTTP := len(result.ExternalHTTPClients) > 0
	var b strings.Builder
	b.WriteString("# Generated by Extent. Edit intentionally; Extent treats this as the observability contract.\n")
	b.WriteString("service:\n")
	b.WriteString("  name: " + name + "\n")
	b.WriteString("  namespace: local\n")
	b.WriteString("  environment: development\n\n")
	b.WriteString("signals:\n")
	b.WriteString("  traces: true\n")
	b.WriteString("  metrics: true\n")
	b.WriteString("  logs: true\n\n")
	b.WriteString("instrumentation:\n")
	b.WriteString("  http: true\n")
	b.WriteString("  database: " + boolString(database) + "\n")
	b.WriteString("  redis: " + boolString(contains(result.DatabaseLibraries, "redis")) + "\n")
	b.WriteString("  queues: " + boolString(queues) + "\n")
	b.WriteString("  external_http: " + boolString(externalHTTP) + "\n")
	b.WriteString("  logs_correlation: true\n\n")
	b.WriteString("slo:\n")
	b.WriteString("  http_latency_p95_ms: 300\n")
	b.WriteString("  error_rate_percent: 1\n")
	b.WriteString("  availability_percent: 99.5\n\n")
	b.WriteString("sampling:\n")
	b.WriteString("  local: always_on\n")
	b.WriteString("  heavy_load: tail_sampling\n\n")
	b.WriteString("redaction:\n")
	b.WriteString("  headers:\n")
	b.WriteString("    - authorization\n")
	b.WriteString("    - cookie\n")
	b.WriteString("  db_statement: sanitize\n")
	b.WriteString("  request_body: disabled\n")
	return b.String()
}

func boolString(value bool) string {
	if value {
		return "true"
	}
	return "false"
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
