package contract

import (
	"github.com/Anubisx404/Extent/internal/analyzer"
	"github.com/Anubisx404/Extent/internal/config"
	"strings"
)

func Render(result analyzer.Result) string {
	c := Build(result)
	b, _ := config.Marshal(c)
	return "# Generated by Extent. Edit intentionally; Extent treats this as the observability contract.\n" + string(b)
}

func Build(result analyzer.Result) config.Config {
	c := config.Defaults()
	if strings.TrimSpace(result.ServiceName) != "" {
		c.Service.Name = result.ServiceName
	} else {
		c.Service.Name = "app"
	}
	c.Instrumentation.Database = len(result.DatabaseLibraries) > 0
	c.Instrumentation.Redis = contains(result.DatabaseLibraries, "redis")
	c.Instrumentation.Queues = len(result.Queues) > 0
	c.Instrumentation.ExternalHTTP = len(result.ExternalHTTPClients) > 0
	return c
}
func contains(values []string, want string) bool {
	for _, v := range values {
		if v == want {
			return true
		}
	}
	return false
}
