package instrumenter

import (
	"bytes"
	"encoding/json"
	"errors"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"extent/internal/codemods"
)

type Options struct {
	Force           bool
	Mode            string
	DryRun          bool
	Undo            bool
	ShowDiff        bool
	RunDeepCodemods bool
}

type Result struct {
	ChangedFiles []string `json:"changedFiles"`
	Messages     []string `json:"messages"`
	Diff         string   `json:"diff,omitempty"`
}

const marker = "extent:otel"

var nodeDependencies = []string{
	"@opentelemetry/api",
	"@opentelemetry/sdk-node",
	"@opentelemetry/auto-instrumentations-node",
	"@opentelemetry/exporter-trace-otlp-http",
	"@opentelemetry/exporter-metrics-otlp-http",
	"@opentelemetry/exporter-logs-otlp-http",
	"@opentelemetry/api-logs",
	"@opentelemetry/sdk-logs",
	"@opentelemetry/sdk-metrics",
}

var pythonDependencies = []string{
	"opentelemetry-api",
	"opentelemetry-sdk",
	"opentelemetry-exporter-otlp",
	"opentelemetry-instrumentation",
	"opentelemetry-instrumentation-fastapi",
	"opentelemetry-instrumentation-flask",
	"opentelemetry-instrumentation-logging",
	"opentelemetry-instrumentation-requests",
}

var nodeDatabaseInstrumentation = map[string][]string{
	"pg":       {"@opentelemetry/instrumentation-pg"},
	"mysql":    {"@opentelemetry/instrumentation-mysql"},
	"mysql2":   {"@opentelemetry/instrumentation-mysql2"},
	"mongodb":  {"@opentelemetry/instrumentation-mongodb"},
	"mongoose": {"@opentelemetry/instrumentation-mongodb"},
	"redis":    {"@opentelemetry/instrumentation-redis"},
	"ioredis":  {"@opentelemetry/instrumentation-ioredis"},
}

var pythonDatabaseInstrumentation = map[string][]string{
	"sqlalchemy":  {"opentelemetry-instrumentation-sqlalchemy"},
	"psycopg2":    {"opentelemetry-instrumentation-psycopg2"},
	"psycopg":     {"opentelemetry-instrumentation-psycopg"},
	"asyncpg":     {"opentelemetry-instrumentation-asyncpg"},
	"pymongo":     {"opentelemetry-instrumentation-pymongo"},
	"redis":       {"opentelemetry-instrumentation-redis"},
	"mysqlclient": {"opentelemetry-instrumentation-mysql"},
	"pymysql":     {"opentelemetry-instrumentation-pymysql"},
}

func Instrument(root string, opts Options) (Result, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return Result{}, err
	}
	if opts.Mode == "" {
		opts.Mode = "bootstrap"
	}
	if opts.Undo {
		return undo(absRoot)
	}
	if opts.Mode == "zero-code" {
		return zeroCode(absRoot, opts)
	}
	var result Result
	if opts.Mode == "deep" {
		if opts.DryRun || opts.ShowDiff {
			for rel := range codemods.BuildBundle().Files {
				result.ChangedFiles = append(result.ChangedFiles, rel)
			}
		} else {
			changed, err := codemods.Write(absRoot, opts.Force)
			if err != nil {
				return Result{}, err
			}
			result.ChangedFiles = append(result.ChangedFiles, changed...)
			if opts.RunDeepCodemods {
				run, err := codemods.Run(absRoot)
				for _, command := range run.Commands {
					result.Messages = append(result.Messages, "ran codemod command: "+strings.Join(command.Command, " "))
				}
				result.Messages = append(result.Messages, run.Output...)
				if err != nil {
					return result, err
				}
			}
		}
	}
	if exists(filepath.Join(absRoot, "package.json")) {
		changed, err := instrumentNode(absRoot, opts)
		if err != nil {
			return Result{}, err
		}
		result.ChangedFiles = append(result.ChangedFiles, changed...)
	}
	if exists(filepath.Join(absRoot, "requirements.txt")) || exists(filepath.Join(absRoot, "main.py")) || exists(filepath.Join(absRoot, "app.py")) {
		changed, err := instrumentPython(absRoot, opts)
		if err != nil {
			return Result{}, err
		}
		result.ChangedFiles = append(result.ChangedFiles, changed...)
	}
	if exists(filepath.Join(absRoot, "go.mod")) {
		changed, err := instrumentGo(absRoot, opts)
		if err != nil {
			return Result{}, err
		}
		result.ChangedFiles = append(result.ChangedFiles, changed...)
	}
	if len(result.ChangedFiles) == 0 {
		result.Messages = append(result.Messages, "no supported source injection changes were needed")
	}
	sort.Strings(result.ChangedFiles)
	return result, nil
}

func zeroCode(root string, opts Options) (Result, error) {
	content := `# Generated by Extent for zero-code instrumentation.
# Node:
NODE_OPTIONS=--require @opentelemetry/auto-instrumentations-node/register

# Python:
OTEL_PYTHON_LOG_CORRELATION=true
# Run with: opentelemetry-instrument python app.py

# Java:
# JAVA_TOOL_OPTIONS=-javaagent:opentelemetry-javaagent.jar

# .NET:
# CORECLR_ENABLE_PROFILING=1
`
	path := filepath.Join(root, "extent.zero-code.env")
	if opts.DryRun || opts.ShowDiff {
		return Result{ChangedFiles: []string{"extent.zero-code.env"}, Diff: diffFor("extent.zero-code.env", "", content)}, nil
	}
	if writeIfChanged(path, content) {
		return Result{ChangedFiles: []string{"extent.zero-code.env"}}, nil
	}
	return Result{Messages: []string{"zero-code file already current"}}, nil
}

func undo(root string) (Result, error) {
	targets := []string{
		"extent.instrumentation.js",
		"extent.instrumentation.mjs",
		"extent_instrumentation.py",
		"extent.zero-code.env",
		"internal/observability/otel.go",
		"extent.codemods",
	}
	var changed []string
	for _, rel := range targets {
		path := filepath.Join(root, rel)
		if exists(path) {
			if err := os.RemoveAll(path); err != nil {
				return Result{}, err
			}
			changed = append(changed, rel)
		}
	}
	return Result{ChangedFiles: changed}, nil
}

func instrumentNode(root string, opts Options) ([]string, error) {
	var changed []string
	pkgPath := filepath.Join(root, "package.json")
	pkgData, err := os.ReadFile(pkgPath)
	if err != nil {
		return nil, err
	}
	var pkg map[string]any
	if err := json.Unmarshal(pkgData, &pkg); err != nil {
		return nil, err
	}
	isESM := pkg["type"] == "module"

	depsChanged := false
	if opts.Mode == "deep" || opts.Mode == "bootstrap" {
		depsChanged = addNodeDependencies(pkg)
	}
	if depsChanged {
		changed = append(changed, "package.json")
	}
	if !opts.DryRun && !opts.ShowDiff && depsChanged {
		out, err := json.MarshalIndent(pkg, "", "  ")
		if err != nil {
			return nil, err
		}
		if err := os.WriteFile(pkgPath, append(out, '\n'), 0644); err != nil {
			return nil, err
		}
	}

	bootstrapName := "extent.instrumentation.js"
	bootstrap := nodeCJSBootstrap
	injection := `require("./extent.instrumentation"); // extent:otel`
	if isESM {
		bootstrapName = "extent.instrumentation.mjs"
		bootstrap = nodeESMBootstrap
		injection = `import "./extent.instrumentation.mjs"; // extent:otel`
	}
	bootstrapPath := filepath.Join(root, bootstrapName)
	if wouldChange(bootstrapPath, bootstrap) {
		changed = append(changed, bootstrapName)
		if !opts.DryRun && !opts.ShowDiff {
			writeIfChanged(bootstrapPath, bootstrap)
		}
	}

	entrypoint := firstExisting(root, []string{"server.js", "index.js", "src/server.js", "src/index.js"})
	if entrypoint == "" {
		return changed, nil
	}
	rel, err := filepath.Rel(root, entrypoint)
	if err != nil {
		return nil, err
	}
	rel = filepath.ToSlash(rel)
	if needsMarker(entrypoint) {
		changed = append(changed, rel)
		if !opts.DryRun && !opts.ShowDiff {
			if _, err := prependLineIfMissing(entrypoint, injection); err != nil {
				return nil, err
			}
		}
	}
	return changed, nil
}

func instrumentGo(root string, opts Options) ([]string, error) {
	var changed []string
	modulePath := goModulePath(filepath.Join(root, "go.mod"))
	if modulePath == "" {
		modulePath = "app"
	}
	bootstrapRel := "internal/observability/otel.go"
	bootstrapPath := filepath.Join(root, filepath.FromSlash(bootstrapRel))
	bootstrap := goBootstrap
	if wouldChange(bootstrapPath, bootstrap) {
		changed = append(changed, bootstrapRel)
		if !opts.DryRun && !opts.ShowDiff {
			writeIfChanged(bootstrapPath, bootstrap)
		}
	}
	entrypoint := firstExisting(root, []string{"main.go"})
	if entrypoint == "" {
		return changed, nil
	}
	importPath := modulePath + "/internal/observability"
	if goImportMissing(entrypoint, importPath) {
		rel, err := filepath.Rel(root, entrypoint)
		if err != nil {
			return nil, err
		}
		changed = append(changed, filepath.ToSlash(rel))
		if !opts.DryRun && !opts.ShowDiff {
			if err := addGoBlankImport(entrypoint, importPath); err != nil {
				return nil, err
			}
		}
	}
	return changed, nil
}

func addNodeDependencies(pkg map[string]any) bool {
	deps, _ := pkg["dependencies"].(map[string]any)
	if deps == nil {
		deps = map[string]any{}
		pkg["dependencies"] = deps
	}
	changed := false
	for _, dep := range nodeDependencies {
		if _, ok := deps[dep]; !ok {
			deps[dep] = "latest"
			changed = true
		}
	}
	existingDeps := map[string]bool{}
	for dep := range deps {
		existingDeps[dep] = true
	}
	for appDep, instrumentationDeps := range nodeDatabaseInstrumentation {
		if !existingDeps[appDep] {
			continue
		}
		for _, dep := range instrumentationDeps {
			if _, ok := deps[dep]; !ok {
				deps[dep] = "latest"
				changed = true
			}
		}
	}
	return changed
}

func goModulePath(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1]
		}
	}
	return ""
}

func goImportMissing(path, importPath string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return !strings.Contains(string(data), strconv.Quote(importPath))
}

func addGoBlankImport(path, importPath string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, data, parser.ParseComments)
	if err != nil {
		return err
	}
	spec := &ast.ImportSpec{
		Name: ast.NewIdent("_"),
		Path: &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(importPath)},
	}
	inserted := false
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.IMPORT {
			continue
		}
		gen.Specs = append(gen.Specs, spec)
		inserted = true
		break
	}
	if !inserted {
		file.Decls = append([]ast.Decl{&ast.GenDecl{Tok: token.IMPORT, Specs: []ast.Spec{spec}}}, file.Decls...)
	}
	var out bytes.Buffer
	if err := format.Node(&out, fset, file); err != nil {
		return err
	}
	return os.WriteFile(path, out.Bytes(), 0644)
}

func instrumentPython(root string, opts Options) ([]string, error) {
	var changed []string
	bootstrapPath := filepath.Join(root, "extent_instrumentation.py")
	if wouldChange(bootstrapPath, pythonBootstrap) {
		changed = append(changed, "extent_instrumentation.py")
		if !opts.DryRun && !opts.ShowDiff {
			writeIfChanged(bootstrapPath, pythonBootstrap)
		}
	}
	requirementsPath := filepath.Join(root, "requirements.txt")
	pythonDeps := append([]string{}, pythonDependencies...)
	pythonDeps = append(pythonDeps, pythonDBInstrumentationFor(requirementsPath)...)
	if requirementsNeed(requirementsPath, pythonDeps) {
		changed = append(changed, "requirements.txt")
		if !opts.DryRun && !opts.ShowDiff {
			addRequirements(requirementsPath, pythonDeps)
		}
	}
	entrypoint := firstExisting(root, []string{"main.py", "app.py"})
	if entrypoint == "" {
		return changed, nil
	}
	rel, err := filepath.Rel(root, entrypoint)
	if err != nil {
		return nil, err
	}
	if needsMarker(entrypoint) {
		changed = append(changed, filepath.ToSlash(rel))
		if !opts.DryRun && !opts.ShowDiff {
			if _, err := prependLineIfMissing(entrypoint, "import extent_instrumentation  # extent:otel"); err != nil {
				return nil, err
			}
		}
	}
	return changed, nil
}

func diffFor(path, before, after string) string {
	var b strings.Builder
	b.WriteString("--- " + path + "\n")
	b.WriteString("+++ " + path + "\n")
	if before != "" {
		b.WriteString("-" + before + "\n")
	}
	if after != "" {
		for _, line := range strings.Split(strings.TrimRight(after, "\n"), "\n") {
			b.WriteString("+" + line + "\n")
		}
	}
	return b.String()
}

func pythonDBInstrumentationFor(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	text := strings.ToLower(string(data))
	var packages []string
	seen := map[string]bool{}
	for appDep, instrumentationDeps := range pythonDatabaseInstrumentation {
		if !strings.Contains(text, strings.ToLower(appDep)) {
			continue
		}
		for _, dep := range instrumentationDeps {
			if !seen[dep] {
				packages = append(packages, dep)
				seen[dep] = true
			}
		}
	}
	sort.Strings(packages)
	return packages
}

func addRequirements(path string, packages []string) bool {
	if !requirementsNeed(path, packages) {
		return false
	}
	existing := map[string]bool{}
	var lines []string
	if data, err := os.ReadFile(path); err == nil {
		lines = strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
		for _, line := range lines {
			name := strings.TrimSpace(strings.Split(strings.Split(line, "==")[0], ">=")[0])
			if name != "" && !strings.HasPrefix(name, "#") {
				existing[strings.ToLower(name)] = true
			}
		}
	}
	for _, pkg := range packages {
		if !existing[strings.ToLower(pkg)] {
			lines = append(lines, pkg)
		}
	}
	content := strings.TrimSpace(strings.Join(lines, "\n")) + "\n"
	_ = os.WriteFile(path, []byte(content), 0644)
	return true
}

func requirementsNeed(path string, packages []string) bool {
	existing := map[string]bool{}
	if data, err := os.ReadFile(path); err == nil {
		lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
		for _, line := range lines {
			name := strings.TrimSpace(strings.Split(strings.Split(line, "==")[0], ">=")[0])
			if name != "" && !strings.HasPrefix(name, "#") {
				existing[strings.ToLower(name)] = true
			}
		}
	}
	for _, pkg := range packages {
		if !existing[strings.ToLower(pkg)] {
			return true
		}
	}
	return false
}

func firstExisting(root string, candidates []string) string {
	for _, candidate := range candidates {
		path := filepath.Join(root, filepath.FromSlash(candidate))
		if exists(path) {
			return path
		}
	}
	return ""
}

func prependLineIfMissing(path, line string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	text := string(data)
	if strings.Contains(text, marker) {
		return false, nil
	}
	if err := os.WriteFile(path, []byte(line+"\n"+text), 0644); err != nil {
		return false, err
	}
	return true, nil
}

func needsMarker(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return !strings.Contains(string(data), marker)
}

func wouldChange(path, content string) bool {
	data, err := os.ReadFile(path)
	return err != nil || string(data) != content
}

func writeIfChanged(path, content string) bool {
	if data, err := os.ReadFile(path); err == nil && string(data) == content {
		return false
	}
	_ = os.MkdirAll(filepath.Dir(path), 0755)
	_ = os.WriteFile(path, []byte(content), 0644)
	return true
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func EnsureSupported(root string) error {
	if !exists(filepath.Join(root, "package.json")) && !exists(filepath.Join(root, "requirements.txt")) {
		return errors.New("no supported Node or Python project files found")
	}
	return nil
}

const nodeCJSBootstrap = `// Generated by Extent. Keep this file imported before application code.
const { logs } = require("@opentelemetry/api-logs");
const { NodeSDK } = require("@opentelemetry/sdk-node");
const { LoggerProvider, BatchLogRecordProcessor } = require("@opentelemetry/sdk-logs");
const { PeriodicExportingMetricReader } = require("@opentelemetry/sdk-metrics");
const { getNodeAutoInstrumentations } = require("@opentelemetry/auto-instrumentations-node");
const { OTLPTraceExporter } = require("@opentelemetry/exporter-trace-otlp-http");
const { OTLPMetricExporter } = require("@opentelemetry/exporter-metrics-otlp-http");
const { OTLPLogExporter } = require("@opentelemetry/exporter-logs-otlp-http");

const loggerProvider = new LoggerProvider();
loggerProvider.addLogRecordProcessor(new BatchLogRecordProcessor(new OTLPLogExporter()));
logs.setGlobalLoggerProvider(loggerProvider);

const sdk = new NodeSDK({
  traceExporter: new OTLPTraceExporter(),
  metricReader: new PeriodicExportingMetricReader({
    exporter: new OTLPMetricExporter(),
  }),
  instrumentations: [getNodeAutoInstrumentations({
    "@opentelemetry/instrumentation-pg": {
      enhancedDatabaseReporting: true,
      requireParentSpan: true,
    },
    "@opentelemetry/instrumentation-mysql": {
      enhancedDatabaseReporting: true,
    },
    "@opentelemetry/instrumentation-mongodb": {
      enhancedDatabaseReporting: true,
    },
    "@opentelemetry/instrumentation-redis": {
      requireParentSpan: true,
    },
    "@opentelemetry/instrumentation-http": {
      headersToSpanAttributes: {
        client: { requestHeaders: ["x-request-id"], responseHeaders: ["x-request-id"] },
        server: { requestHeaders: ["x-request-id"], responseHeaders: ["x-request-id"] },
      },
    },
  })],
});

sdk.start();
`

const nodeESMBootstrap = `// Generated by Extent. Keep this file imported before application code.
import { logs } from "@opentelemetry/api-logs";
import { NodeSDK } from "@opentelemetry/sdk-node";
import { LoggerProvider, BatchLogRecordProcessor } from "@opentelemetry/sdk-logs";
import { PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { OTLPMetricExporter } from "@opentelemetry/exporter-metrics-otlp-http";
import { OTLPLogExporter } from "@opentelemetry/exporter-logs-otlp-http";

const loggerProvider = new LoggerProvider();
loggerProvider.addLogRecordProcessor(new BatchLogRecordProcessor(new OTLPLogExporter()));
logs.setGlobalLoggerProvider(loggerProvider);

const sdk = new NodeSDK({
  traceExporter: new OTLPTraceExporter(),
  metricReader: new PeriodicExportingMetricReader({
    exporter: new OTLPMetricExporter(),
  }),
  instrumentations: [getNodeAutoInstrumentations({
    "@opentelemetry/instrumentation-pg": {
      enhancedDatabaseReporting: true,
      requireParentSpan: true,
    },
    "@opentelemetry/instrumentation-mysql": {
      enhancedDatabaseReporting: true,
    },
    "@opentelemetry/instrumentation-mongodb": {
      enhancedDatabaseReporting: true,
    },
    "@opentelemetry/instrumentation-redis": {
      requireParentSpan: true,
    },
    "@opentelemetry/instrumentation-http": {
      headersToSpanAttributes: {
        client: { requestHeaders: ["x-request-id"], responseHeaders: ["x-request-id"] },
        server: { requestHeaders: ["x-request-id"], responseHeaders: ["x-request-id"] },
      },
    },
  })],
});

sdk.start();
`

const goBootstrap = `// Package observability initializes OpenTelemetry for the service.
// Generated by Extent. Keep this package imported before application code.
package observability

import (
	"context"
	"log"
	"os"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
)

func init() {
	serviceName := os.Getenv("OTEL_SERVICE_NAME")
	if serviceName == "" {
		serviceName = "go-service"
	}
	exporter, err := otlptracehttp.New(context.Background())
	if err != nil {
		log.Printf("extent: failed to create OTLP trace exporter: %v", err)
		return
	}
	provider := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName(serviceName),
		)),
	)
	otel.SetTracerProvider(provider)
}
`

const pythonBootstrap = `"""Generated by Extent. Import before application code."""

from opentelemetry import trace
from opentelemetry._logs import set_logger_provider
from opentelemetry.instrumentation.logging import LoggingInstrumentor
from opentelemetry.instrumentation.requests import RequestsInstrumentor
from opentelemetry.metrics import set_meter_provider
from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.exporter.otlp.proto.http._log_exporter import OTLPLogExporter
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

try:
    from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
except Exception:
    SQLAlchemyInstrumentor = None

try:
    from opentelemetry.instrumentation.psycopg2 import Psycopg2Instrumentor
except Exception:
    Psycopg2Instrumentor = None

resource = Resource.create({})
trace_provider = TracerProvider(resource=resource)
trace_provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter()))
trace.set_tracer_provider(trace_provider)

metric_reader = PeriodicExportingMetricReader(OTLPMetricExporter())
set_meter_provider(MeterProvider(resource=resource, metric_readers=[metric_reader]))

logger_provider = LoggerProvider(resource=resource)
logger_provider.add_log_record_processor(BatchLogRecordProcessor(OTLPLogExporter()))
set_logger_provider(logger_provider)
LoggingInstrumentor().instrument(set_logging_format=True)
RequestsInstrumentor().instrument()
if SQLAlchemyInstrumentor is not None:
    SQLAlchemyInstrumentor().instrument(enable_commenter=True, commenter_options={})
if Psycopg2Instrumentor is not None:
    Psycopg2Instrumentor().instrument(enable_commenter=True)
`
