package templates

import (
	"crypto/rand"
	"errors"
	"math/big"
	"os"
	"strings"

	"github.com/Anubisx404/Extent/internal/stack"
)

const grafanaPasswordLength = 24

const passwordAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// generateGrafanaPassword returns a uniformly random alphanumeric password.
// Alphanumeric-only keeps the value safe in an env file and in compose interpolation.
func generateGrafanaPassword() (string, error) {
	max := big.NewInt(int64(len(passwordAlphabet)))
	out := make([]byte, 0, grafanaPasswordLength)
	for len(out) < grafanaPasswordLength {
		n, err := rand.Int(rand.Reader, max)
		if err != nil {
			return "", errors.New("generate Grafana password: " + err.Error())
		}
		out = append(out, passwordAlphabet[n.Int64()])
	}
	return string(out), nil
}

// observabilityEnv returns the content of .env.observability for a project.
//   - No file yet: the base env block plus a freshly generated Grafana password.
//   - File with a password: returned unchanged, so re-apply never churns it.
//   - File without a password (written by an older apply): the password line is
//     filled in or appended; the rest of the file is kept. addedPassword reports that.
func observabilityEnv(existing string, exists bool) (content string, addedPassword bool, err error) {
	password, err := generateGrafanaPassword()
	if err != nil {
		return "", false, err
	}
	if !exists || strings.TrimSpace(existing) == "" {
		return envObservability + grafanaEnvSection(password), exists, nil
	}
	if stack.ParseEnv(existing)[stack.GrafanaPasswordKey] != "" {
		return existing, false, nil
	}
	lines := strings.Split(strings.TrimRight(existing, "\n"), "\n")
	filled := false
	for i, line := range lines {
		key, _, ok := strings.Cut(line, "=")
		if ok && strings.TrimSpace(key) == stack.GrafanaPasswordKey {
			lines[i] = stack.GrafanaPasswordKey + "=" + password
			filled = true
		}
	}
	out := strings.Join(lines, "\n") + "\n"
	if !filled {
		out += stack.GrafanaPasswordKey + "=" + password + "\n"
	}
	return out, true, nil
}

func grafanaEnvSection(password string) string {
	return "\n# Grafana admin login. Generated by extent apply and kept on re-apply.\n" +
		stack.GrafanaUserKey + "=" + stack.DefaultGrafanaUser + "\n" +
		stack.GrafanaPasswordKey + "=" + password + "\n"
}

// readOptionalFile returns the file content and whether it exists. A missing file is not an error.
func readOptionalFile(path string) (string, bool, error) {
	data, err := os.ReadFile(path)
	if err == nil {
		return string(data), true, nil
	}
	if os.IsNotExist(err) {
		return "", false, nil
	}
	return "", false, err
}
